'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("RockBox_PSGroove_Installer.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _1_Click_InstallP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1_Click_InstallP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1ClickInstall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1ClickInstall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1ClickInstallO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1ClickInstallO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1ClickUninstall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1ClickUninstall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1ClickUninstallO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1ClickUninstallO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1ClickUninstallP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1ClickUninstallP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _4G() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("4G", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _4G_Photo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("4G-Photo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property C200() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("C200", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Create_loader_cfg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Create_loader.cfg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Create_loader_cfgO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Create_loader.cfgO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Create_loader_cfgP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Create_loader.cfgP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Donate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Donate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DonateO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DonateO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DonateP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DonateP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Download() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Download", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DownloadO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DownloadO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DownloadP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DownloadP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property E200() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("E200", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Instal_uninstalllO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Instal_uninstalllO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Instal_uninstallP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Instal_uninstallP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Install() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Install", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Install_uninstall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Install_uninstall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property InstallO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("InstallO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property InstallP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("InstallP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property iPL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iPL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MHUFreeStore() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MHUFreeStore", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Mini_1G() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mini-1G", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Mini_2G() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mini-2G", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Nano_1G() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nano-1G", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property No_thanks() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("No_thanks", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property No_thanksO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("No_thanksO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property No_thanksP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("No_thanksP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Official_Site() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Official_Site", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Official_SiteO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Official_SiteO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Official_SiteP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Official_SiteP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PlugInPreview() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PlugInPreview", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PSX_Scene() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PSX-Scene", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PSX_SceneO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PSX-SceneO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PSX_SceneP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PSX-SceneP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Text_Box() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Text-Box", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Uninstall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Uninstall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property UninstallO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UninstallO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property UninstallP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UninstallP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Video() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Video", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
